/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WowXYZERC20__factory } from "./WowXYZERC20__factory.js";
export {ReputationAgent__factory} from "./ReputationAgent__factory.js"